// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student__System_With_Code_First.Context;

#nullable disable

namespace Student__System_With_Code_First.Migrations
{
    [DbContext(typeof(Db_Context))]
    partial class Db_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Student__System_With_Code_First.Models.Student_Model", b =>
                {
                    b.Property<int>("stud_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stud_id"));

                    b.Property<string>("stud_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stud_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stud_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stud_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stud_id");

                    b.ToTable("student_tbl");
                });
#pragma warning restore 612, 618
        }
    }
}
